# Site settings
title: Daisy's Podcast Review
email: daixy8982@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A new podcast review every day.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://idaisy.github.io" # the base hostname & protocol for your site
#twitter_username: 
github_username:  idaisy
#linkedin_url: "http://cn.linkedin.com/in/scateu"

imageurl: "http://idaisy.github.io/images"

# Build settings
markdown: kramdown
#highlighter: pygments
highlighter: rouge
